import { Listing } from './listing.model';

export const HOUSING: Listing[] = [
  new Listing("Fixer Upper- Distressed - Divorce - Estate -Foreclosure -Job Transfer", 0,
    "https://images.craigslist.org/00v0v_iV6HScNavqJ_600x450.jpg", "PRINCIPLES ONLY!!! - I am looking for any Fixer Upper House or Mobile with Land. - Take Over Payments - No Bank Involvement - No Project Too Big - Foreclosure - Job Transfer - Jail - Death in the Family - Estate - Divorce - Fixer. If you have a property that the bank will not finance then call me. - Free advice - I can Help. Contact me at 503 seven three four 0681. You can leave a message if I am Driving. Thank you.", "Portland Metro Area", 1),
  new Listing("$1530 / 1br - 597ft2 - 24 Hour Fitness Gym Access, Washer & Dryer In Each Home!", 1530,
    "https://images.craigslist.org/00L0L_g6hXVcVqsR0_600x450.jpg", "20 Pettygrove is 6 story building located in a residential area of NW Portland featuring spaciously designed studios, 1 bedroom and 2 bedroom apartment homes. We are just walking distance from the upscale Pearl District, 3 dog parks, a huge array of shopping, one of a kind restaurants, locally owned boutiques, miles of nearby sites to explore, major bus lines and the Streetcar. Come in today to see why the Alphabet District is the place to be. Northwest is the premium place to be in Portland, so come see us today!\n-Granite Countertops\n-24 Hour Fitness Gym\n-Controlled Access\n-City Views In Select Homes\n-Additional Storage\n-Online Payments Available\n-Black appliances\n-Washer & Dryer In Each Home\n-Dishwasher", "NW Portland", 2),
  new Listing("$399000 / 4br - 2462ft2 - River Front Home of Your Dreams!", 399000,
    "https://images.craigslist.org/00d0d_3tF3z4GeNzC_600x450.jpg", "4bd/3bth well-maintained cedar bevel siding home located along the Nestucca River, majestic trees in a semi-secluded area, Some of this home's outstanding features: Main level a LG master bd & master ba, vaulted ceilings, open floor plan, heat pump, & a new roof in 2015. An Oversized deck with a covered area, garden shed, inviting yard, LG 3 car Garage, gas fireplace.\nCall Nick or Ike for MORE details", "Beaver, OR", 3),
  new Listing("1br - Cozy log cabin, perfect for romantic weekend retreat!", 100,
    "https://images.craigslist.org/00E0E_iaKIjSwSZqo_600x450.jpg", "For the same cost of a hotel room, you could stay in a cozy little one bedroom log cabin, overlooking the Washougal River. The cabin is located fifteen minutes from the 205 bridge, and twenty minutes from the I-5 bridge, at the mouth of the Columbia River Gorge. Close to town, but secluded, we have an abundance of hiking trails and river walks close by. The cabin features an extremely comfortable queen size bed, living room, full kitchen, wood stove, cable TV, DVD player, Wi-Fi and laundry facilities onsite. It would be a great place to escape for a romantic weekend, or a place to find some peace and solitude from the hustle and bustle of life. The rent is $100 per night, and $600 per week. If you are planning a romantic getaway, we could even arrange to have chocolates, wine, and flowers awaiting your arrival. Just let us know, and we'll work out all the details for you. Hope to see you soon!\n$100 a night \n$600 a week \nNo hidden fees!", "Anywhere", 4),
 ];
